module NetboxClientRuby
  module Secrets
    def self.secret_roles: () -> SecretRoles
    def self.secrets: () -> Secrets
    def self.generate_rsa_key_pair: () -> RSAKeyPair
    def self.get_session_key: () -> SessionKey

    def self.secret_role: (Integer | String id) -> SecretRole
    def self.secret: (Integer | String id) -> Secret

    def self.session_key: () -> String?
    def self.session_key=: (String?) -> String?

    def secret_roles: () -> SecretRoles
    def secrets: () -> Secrets
    def generate_rsa_key_pair: () -> RSAKeyPair
    def get_session_key: () -> SessionKey

    def secret_role: (Integer | String id) -> SecretRole
    def secret: (Integer | String id) -> Secret

    def session_key: () -> String?
    def session_key=: (String?) -> String?

    class SecretRole
      include Entity

      def name: () -> String?
      def slug: () -> String?
      def users: () -> untyped
      def groups: () -> untyped
    end

    class SecretRoles
      include Entities[SecretRole]
    end

    class Secret
      include Entity

      def device: () -> DCIM::Device?
      def role: () -> SecretRole?
      def name: () -> String?
      def plaintext: () -> String?
      def hash: () -> String?
    end

    class Secrets
      include Entities[Secret]
    end

    class RSAKeyPair
      include Entity

      def public_key: () -> String?
      def private_key: () -> String?
    end

    class SessionKey
      include Entity

      def session_key: () -> String?
    end
  end
end
